baseURL = 'https://me.gunjandhanuka.com/'
languageCode = 'en-us'
title = 'Gunjan Dhanuka'
theme = 'PaperMod'
disqusShortname = 'gunjandhanuka'
enableEmoji = true
googleAnalytics = "G-GVK924BEC6"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
ShowShareButtons = true
ShowReadingTime = true
ShowToc = true
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
comments = true
math = true

[params.profileMode]
enabled = true
title = "Gunjan Dhanuka"
subtitle = "CSE IITG'24 | Traveller | Techie with an itch for writing" 
imageUrl = "https://gunjandhanuka.com/images/gd_new_pic.jpg"
imageTitle = "Profile Picture"
imageWidth = 240
imageHeight = 240

[[menu.main]]
identifier = "posts"
name = "Blogs"
url = "/posts/"
weight = 30

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 30

[[menu.main]]
identifier = "cv"
name = "CV"
url = "https://gunjandhanuka.com/data/GunjanResume.pdf"
weight = 20

[[params.profileMode.buttons]]
name = "Blogs"
url = "/posts"

[[params.profileMode.buttons]]
name = "CV"
url = "https://gunjandhanuka.com/data/GunjanResume.pdf"

[[params.profileMode.buttons]]
name = "Academic Site"
url = "https://gunjandhanuka.com/"

[[params.socialIcons]]
name = "Linkedin"
url = "https://in.linkedin.com/in/gunjan-dhanuka/"

[[params.socialIcons]]
name = "Instagram"
url = "https://www.instagram.com/gunjan_dhanuka/"

[[params.socialIcons]]
name = "Medium"
url = "https://gunjan-dhanuka.medium.com/"

[[params.socialIcons]]
name = "Github"
url = "https://github.com/GunjanDhanuka"

[[params.socialIcons]]
name = "Email"
url = "https://gunjan-dhanuka.medium.com/"

