baseURL = 'https://me.gunjandhanuka.com'
languageCode = 'en-us'
title = 'Gunjan Dhanuka'
theme = 'PaperMod'

[params.profileMode]
enabled = true
title = "Gunjan Dhanuka"
subtitle = "CSE IITG '24 | Traveller | YouTuber | Quizzard"
imageUrl = "https://gunjandhanuka.com/images/gd_new_pic.jpg"
imageTitle = "Profile Picture"
imageWidth = 120
imageHeight = 120

[[params.profileMode.buttons]]
name = "Blogs"
url = "/posts"

[[params.profileMode.buttons]]
name = "Github"
url = "https://github.com/GunjanDhanuka"

[[params.profileMode.buttons]]
name = "CV"
url = "https://gunjandhanuka.com/data/GunjanResume.pdf"

[[params.socialIcons]]
name = "Instagram"
url = "<link>"

[[params.socialIcons]]
name = "<platform 2>"
url = "<link2>"

